[package]
name = "markdownif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "markdownif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
pulldown-cmark = { version = "0.5", default-features = false }